---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: planespotter-frontend
  namespace: planespotter
  labels:
    app: planespotter
    tier: app-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planespotter
  template:
    metadata:
      labels:
        app: planespotter
        tier: app-tier
    spec:
      containers:
      - name: adsb-sync
        image: yfauser/planespotter-frontend:6339bcd2301757bdc72643c59c0008a63128ac04
        imagePullPolicy: IfNotPresent
        env:
        - name: PLANESPOTTER_API_ENDPOINT
          value: planespotter-svc
